import { Machine, MachineType, SparePart, RepairTicket, PPMSchedule, UserProfile, PartRequisition } from '@/types/cmms';

export const SEED_USERS: UserProfile[] = [
  {
    uid: 'CEO-01',
    name: 'Dr. K. Ramanathan',
    email: 'ceo@textech.garments',
    role: 'CEO',
    title: 'Chief Executive Officer (Managing Director)',
  },
  {
    uid: 'ADM-01',
    name: 'V. Sundaram',
    email: 'admin@textech.garments',
    role: 'ADMIN',
    title: 'Plant Administrator & Asset Director',
  },
  {
    uid: 'MEC-01',
    name: 'Ramesh Kumar',
    email: 'seniormechanic@textech.garments',
    role: 'SENIOR_MECHANIC',
    title: 'Senior Sewing Master Mechanic',
  },
  {
    uid: 'MEC-08',
    name: 'Suresh Babu',
    email: 'mechanic@textech.garments',
    role: 'MECHANIC',
    title: 'Line Sewing Mechanic',
  },
  {
    uid: 'STR-01',
    name: 'M. Arumugam',
    email: 'stores@textech.garments',
    role: 'STORE_PERSON',
    title: 'Tool Crib & Store In-Charge',
  },
];

export const SEED_MACHINES: Machine[] = [
  // ==================== 1. PRODUCTION MACHINERY (OVERLOCK, FLATLOCK, SINGLE NEEDLE) ====================
  {
    id: 'MC-SN-KAJA-101',
    name: 'Brother KAJA Buttonhole Machine (Line 01 - St.04)',
    brand: 'Brother',
    model: 'HE-800B KAJA Electronic',
    category: 'MACHINE',
    machineClass: 'SINGLE_NEEDLE',
    type: 'SN_BROTHER_KAJA',
    typeName: 'Brother KAJA',
    motorType: 'SERVO',
    purchaseDate: '2023-04-12',
    cost: 1850,
    status: 'ACTIVE',
    currentLine: 'Line 01',
    stationNo: 'Station 04',
    operator: 'K. Kavitha',
    totalDowntimeMinutes: 118,
    ageYears: 3.4,
    specs: 'Electronic indexer, pulse motor knife drop, 21 preset buttonhole eyelet stitch patterns',
  },
  {
    id: 'MC-OVK-4TH-204',
    name: 'Yamato 4-Thread High-Speed Overlock (Line 02 - St.03)',
    brand: 'Yamato',
    model: 'AZ-8000G / 4-Thread High-Speed',
    category: 'MACHINE',
    machineClass: 'OVERLOCK',
    type: 'OVERLOCK_4_THREAD',
    typeName: '4 Thread Overlock',
    motorType: 'SERVO',
    purchaseDate: '2022-09-18',
    cost: 980,
    status: 'BREAKDOWN',
    currentLine: 'Line 02',
    stationNo: 'Station 03',
    operator: 'S. Murugan',
    totalDowntimeMinutes: 145,
    ageYears: 4.0,
    specs: '4-thread safety stitch, differential feed ratio 1:0.7–1:2, max 7,500 RPM, auto-lubrication',
  },
  {
    id: 'MC-SN-BTK-102',
    name: 'Brother Electronic Bartack (Line 01 - St.07)',
    brand: 'Brother',
    model: 'KE-430FS Direct-Drive Bartack',
    category: 'MACHINE',
    machineClass: 'SINGLE_NEEDLE',
    type: 'SN_BROTHER_BARTACK',
    typeName: 'Brother Bartack',
    motorType: 'SERVO',
    purchaseDate: '2024-02-10',
    cost: 1450,
    status: 'ACTIVE',
    currentLine: 'Line 01',
    stationNo: 'Station 07',
    operator: 'P. Rajeshwari',
    totalDowntimeMinutes: 40,
    ageYears: 2.6,
    specs: 'High-speed 3,200 SPM electronic bartacker, direct-drive servo, 89 programmed patterns',
    previousLine: 'Line 03',
    previousStation: 'Station 04',
    lastMovedAt: '2026-09-19T11:00:00Z',
    lastMovedReason: 'Moved from Line 03 for pocket reinforcing on Line 01',
    lastMovedBy: 'Ramesh Kumar',
    relocationHistory: [
      {
        fromLine: 'Line 03',
        fromStation: 'Station 04',
        toLine: 'Line 01',
        toStation: 'Station 07',
        movedAt: '2026-09-19T11:00:00Z',
        movedBy: 'Ramesh Kumar',
        reason: 'Moved from Line 03 for pocket reinforcing on Line 01',
      },
    ],
  },
  {
    id: 'MC-FLK-CYL-301',
    name: 'Yamato Cylinder Bed Flatlock (Line 02 - St.09)',
    brand: 'Yamato',
    model: 'VG-2700-CB Cylinder Bed',
    category: 'MACHINE',
    machineClass: 'FLATLOCK',
    type: 'FLATLOCK_CYLINDER_BED',
    typeName: 'Cylinder Bed Flatlock',
    motorType: 'SERVO',
    purchaseDate: '2021-11-05',
    cost: 1650,
    status: 'ACTIVE',
    currentLine: 'Line 02',
    stationNo: 'Station 09',
    operator: 'D. Anitha',
    totalDowntimeMinutes: 65,
    ageYears: 4.9,
    specs: 'Tubular garment assembly, 280mm cylinder bed circumference, top and bottom coverstitch',
  },
  {
    id: 'VHC-FLT-001',
    name: 'Godrej Heavy Duty Forklift (Warehouse A)',
    brand: 'Godrej',
    model: 'GX-20',
    category: 'VEHICLE',
    machineClass: 'OTHER',
    type: 'VEHICLE_FORKLIFT',
    typeName: 'Heavy Duty Forklift',
    motorType: 'OTHER',
    purchaseDate: '2021-06-15',
    cost: 1500000,
    status: 'ACTIVE',
    currentLine: 'Warehouse & Storage',
    stationNo: 'Loading Dock A',
    operator: 'R. Velu',
    totalDowntimeMinutes: 120,
    ageYears: 5.2,
    specs: '2 Ton capacity, Diesel/Electric, 3-stage mast',
  },
  {
    id: 'MC-SN-BTN-501',
    name: 'Brother Direct-Drive Button Stitch (Line 03 - St.02)',
    brand: 'Brother',
    model: 'BE-438F Direct-Drive Button Attacher',
    category: 'MACHINE',
    machineClass: 'SINGLE_NEEDLE',
    type: 'SN_BROTHER_BUTTON_STITCH',
    typeName: 'Brother Button Stitch',
    motorType: 'SERVO',
    purchaseDate: '2023-08-20',
    cost: 1350,
    status: 'ACTIVE',
    currentLine: 'Line 03',
    stationNo: 'Station 02',
    operator: 'V. Selvam',
    totalDowntimeMinutes: 20,
    ageYears: 3.1,
    specs: 'Direct-drive lockstitch button sewing, quick-change clamp for 2-hole & 4-hole buttons',
  },
  {
    id: 'MC-SN-KAJA-601',
    name: 'Supreme KAJA Computerized Buttonhole (Line 03 - St.08)',
    brand: 'Supreme',
    model: 'SP-8000 KAJA Indexer',
    category: 'MACHINE',
    machineClass: 'SINGLE_NEEDLE',
    type: 'SN_BROTHER_KAJA',
    typeName: 'Brother KAJA',
    motorType: 'SERVO',
    purchaseDate: '2020-03-14',
    cost: 1950,
    status: 'ACTIVE',
    currentLine: 'Line 03',
    stationNo: 'Station 08',
    operator: 'A. Mary',
    totalDowntimeMinutes: 190,
    ageYears: 6.5,
    specs: 'Computerized buttonhole indexer, pulse motor knife drop, multi-cut buttonhole cycle',
  },
  {
    id: 'MC-OVK-RIB-209',
    name: 'Yamato Rib Thread Overlock (Buffer Standby)',
    brand: 'Yamato',
    model: 'AZ-8500-Rib Attacher',
    category: 'MACHINE',
    machineClass: 'OVERLOCK',
    type: 'OVERLOCK_RIB_THREAD',
    typeName: 'Rib Thread Overlock',
    motorType: 'SERVO',
    purchaseDate: '2024-06-11',
    cost: 1120,
    status: 'BUFFER',
    currentLine: 'Buffer Workshop',
    stationNo: 'Bay B-02',
    operator: 'Standby Buffer',
    totalDowntimeMinutes: 10,
    ageYears: 2.3,
    specs: 'Pneumatic rib collar feeder, tension-controlled rib knit insertion, 7,000 RPM',
  },
  {
    id: 'MC-FLK-HEM-701',
    name: 'Yamato Hemming Flatlock (Line 04 - St.05)',
    brand: 'Yamato',
    model: 'VG-2700-Hemming / UTT',
    category: 'MACHINE',
    machineClass: 'FLATLOCK',
    type: 'FLATLOCK_HEMMING',
    typeName: 'Hemming Flatlock',
    motorType: 'SERVO',
    purchaseDate: '2022-01-20',
    cost: 1550,
    status: 'ACTIVE',
    currentLine: 'Line 04',
    stationNo: 'Station 05',
    operator: 'T. Ganesan',
    totalDowntimeMinutes: 95,
    ageYears: 4.7,
    specs: 'Bottom hem blindfold guide, auto underbed thread trimmer (UTT), 3-needle 5-thread',
  },
  {
    id: 'MC-SN-BTK-109',
    name: 'Supreme Heavy Electronic Bartack (Line 01 - St.02)',
    brand: 'Supreme',
    model: 'SP-430 Bartack-Pro',
    category: 'MACHINE',
    machineClass: 'SINGLE_NEEDLE',
    type: 'SN_BROTHER_BARTACK',
    typeName: 'Brother Bartack',
    motorType: 'SERVO',
    purchaseDate: '2025-01-10',
    cost: 1480,
    status: 'ACTIVE',
    currentLine: 'Line 01',
    stationNo: 'Station 02',
    operator: 'M. Lakshmi',
    totalDowntimeMinutes: 0,
    ageYears: 1.7,
    specs: 'Heavy duty electronic bartacker with digital clamp pressure and programmable reinforcement patterns',
  },
  {
    id: 'MC-FLK-SMC-401',
    name: 'Yamato Small Cylinder Bed Flatlock (Line 04 - St.02)',
    brand: 'Yamato',
    model: 'VG-3721-SCB Small Cylinder',
    category: 'MACHINE',
    machineClass: 'FLATLOCK',
    type: 'FLATLOCK_SMALL_CYLINDER',
    typeName: 'Small Cylinder Bed Flatlock',
    motorType: 'SERVO',
    purchaseDate: '2023-05-15',
    cost: 1720,
    status: 'ACTIVE',
    currentLine: 'Line 04',
    stationNo: 'Station 02',
    operator: 'R. Balamurugan',
    totalDowntimeMinutes: 45,
    ageYears: 3.3,
    specs: '180mm mini cylinder circumference for tubular children cuffs and ankle openings, 5,500 RPM',
  },
  {
    id: 'MC-OVK-LFC-215',
    name: 'Supreme LFC High-Speed Overlock (Line 02 - St.06)',
    brand: 'Supreme',
    model: 'SP-LFC-900 Electronic',
    category: 'MACHINE',
    machineClass: 'OVERLOCK',
    type: 'OVERLOCK_LFC',
    typeName: 'LFC Overlock',
    motorType: 'SERVO',
    purchaseDate: '2024-03-25',
    cost: 990,
    status: 'ACTIVE',
    currentLine: 'Line 02',
    stationNo: 'Station 06',
    operator: 'C. Meena',
    totalDowntimeMinutes: 30,
    ageYears: 2.5,
    specs: 'Light/Fine cloth edge overlock, micro-sensor needle positioning, 6,800 RPM',
    previousLine: 'Line 01',
    previousStation: 'Station 05',
    lastMovedAt: '2026-09-18T14:20:00Z',
    lastMovedReason: 'Rebalanced to Line 02 for light-fabric polo production order',
    lastMovedBy: 'Ramesh Kumar',
    relocationHistory: [
      {
        fromLine: 'Line 01',
        fromStation: 'Station 05',
        toLine: 'Line 02',
        toStation: 'Station 06',
        movedAt: '2026-09-18T14:20:00Z',
        movedBy: 'Ramesh Kumar',
        reason: 'Rebalanced to Line 02 for light-fabric polo production order',
      },
    ],
  },
  {
    id: 'MC-SCRAP-99',
    name: 'Yamato Flat Bed Flatlock (Decommissioned - Scrap Bay)',
    brand: 'Yamato',
    model: 'VF-2500-Flat Bed Series',
    category: 'MACHINE',
    machineClass: 'FLATLOCK',
    type: 'FLATLOCK_FLAT_BED',
    typeName: 'Flat Bed Flatlock',
    motorType: 'CLUTCH',
    purchaseDate: '2018-02-14',
    cost: 1200,
    status: 'SCRAP',
    currentLine: 'Scrap Bay',
    stationNo: 'Salvage Rack 01',
    operator: 'Decommissioned',
    totalDowntimeMinutes: 480,
    ageYears: 8.6,
    specs: 'Decommissioned frame salvaged for looper mechanisms, needle clamp blocks, and flatbed covers',
    previousLine: 'Line 02',
    previousStation: 'Station 08',
    lastMovedAt: '2026-09-12T10:15:00Z',
    lastMovedReason: 'Casting housing fractured; decommissioned and moved to scrap salvage bay',
    lastMovedBy: 'Suresh Babu',
    relocationHistory: [
      {
        fromLine: 'Line 02',
        fromStation: 'Station 08',
        toLine: 'Scrap Bay',
        toStation: 'Salvage Rack 01',
        movedAt: '2026-09-12T10:15:00Z',
        movedBy: 'Suresh Babu',
        reason: 'Casting housing fractured; decommissioned and moved to scrap salvage bay',
      },
    ],
  },

  // ==================== 2. WORK, CUTTING & INSPECTION TABLES ====================
  {
    id: 'TBL-CUT-101',
    name: 'Fabric Spreading & Cutting Table (Line 01)',
    brand: 'Eastman',
    model: 'SpreadMaster-12',
    category: 'TABLE',
    type: 'TABLE_CUTTING',
    typeName: 'Fabric Spreading & Cutting Table',
    purchaseDate: '2022-03-10',
    cost: 1400,
    status: 'ACTIVE',
    currentLine: 'Line 01',
    stationNo: 'Station 01',
    operator: 'M. Perumal',
    totalDowntimeMinutes: 0,
    ageYears: 4.5,
    specs: '12ft x 6ft Air-flotation laminated top with end fabric clamps',
  },
  {
    id: 'TBL-SEW-101',
    name: 'Sewing Station Laminated Table (Line 01 - St.04)',
    brand: 'Featherlite',
    model: 'StitchDesk-Pro',
    category: 'TABLE',
    type: 'TABLE_SEWING',
    typeName: 'Sewing Workstation Table',
    purchaseDate: '2023-04-12',
    cost: 180,
    status: 'ACTIVE',
    currentLine: 'Line 01',
    stationNo: 'Station 04',
    operator: 'K. Kavitha',
    totalDowntimeMinutes: 0,
    ageYears: 3.4,
    specs: 'Heavy steel K-stand with embedded metric measuring rule & drawer',
  },
  {
    id: 'TBL-SEW-102',
    name: 'Sewing Station Laminated Table (Line 01 - St.07)',
    brand: 'Featherlite',
    model: 'StitchDesk-Pro',
    category: 'TABLE',
    type: 'TABLE_SEWING',
    typeName: 'Sewing Workstation Table',
    purchaseDate: '2024-02-10',
    cost: 180,
    status: 'ACTIVE',
    currentLine: 'Line 01',
    stationNo: 'Station 07',
    operator: 'P. Rajeshwari',
    totalDowntimeMinutes: 0,
    ageYears: 2.6,
    specs: 'Anti-vibration rubber feet, recessed waste chute',
  },
  {
    id: 'TBL-SEW-201',
    name: 'Overlock Work Table (Line 02 - St.03)',
    brand: 'Featherlite',
    model: 'OverlockDesk-V2',
    category: 'TABLE',
    type: 'TABLE_SEWING',
    typeName: 'Sewing Workstation Table',
    purchaseDate: '2022-09-18',
    cost: 190,
    status: 'ACTIVE',
    currentLine: 'Line 02',
    stationNo: 'Station 03',
    operator: 'S. Murugan',
    totalDowntimeMinutes: 0,
    ageYears: 4.0,
    specs: 'Wide scoop cutout for suction tube & fabric collection trough',
  },
  {
    id: 'TBL-SEW-202',
    name: 'Flatlock Coverstitch Table (Line 02 - St.09)',
    brand: 'Featherlite',
    model: 'StitchDesk-Pro',
    category: 'TABLE',
    type: 'TABLE_SEWING',
    typeName: 'Sewing Workstation Table',
    purchaseDate: '2021-11-05',
    cost: 180,
    status: 'ACTIVE',
    currentLine: 'Line 02',
    stationNo: 'Station 09',
    operator: 'D. Anitha',
    totalDowntimeMinutes: 0,
    ageYears: 4.9,
    specs: 'Cylinder arm platform insert, spool stand mounting bracket',
  },
  {
    id: 'TBL-INSP-301',
    name: 'Garment Quality Inspection Table with Overhead Canopy (Line 03)',
    brand: 'Godrej',
    model: 'QC-Pro-800',
    category: 'TABLE',
    type: 'TABLE_INSPECTION',
    typeName: 'QC Garment Checking Table',
    purchaseDate: '2023-01-15',
    cost: 480,
    status: 'ACTIVE',
    currentLine: 'Line 03',
    stationNo: 'Station 08',
    operator: 'A. Mary',
    totalDowntimeMinutes: 15,
    ageYears: 3.7,
    specs: '8ft x 4ft Matte white reflection-free top with measurement grid',
  },
  {
    id: 'TBL-HVY-401',
    name: 'Reinforced Denim Assembly Table (Line 04 - St.02)',
    brand: 'SteelCraft',
    model: 'DenimMaster-X',
    category: 'TABLE',
    type: 'TABLE_SEWING',
    typeName: 'Sewing Workstation Table',
    purchaseDate: '2023-05-15',
    cost: 260,
    status: 'ACTIVE',
    currentLine: 'Line 04',
    stationNo: 'Station 02',
    operator: 'R. Balamurugan',
    totalDowntimeMinutes: 0,
    ageYears: 3.3,
    specs: 'Reinforced tubular steel understructure for heavy denim feed',
  },
  {
    id: 'TBL-PACK-01',
    name: 'Final Folding & Poly-Bagging Table (Line 01)',
    brand: 'Featherlite',
    model: 'PackStation-10',
    category: 'TABLE',
    type: 'TABLE_PACKING',
    typeName: 'Final Folding & Poly-Bagging Table',
    purchaseDate: '2023-06-20',
    cost: 320,
    status: 'ACTIVE',
    currentLine: 'Line 01',
    stationNo: 'Station 10',
    operator: 'K. Meenakshi',
    totalDowntimeMinutes: 0,
    ageYears: 3.2,
    specs: 'Upper rack for hangtags, barcode scanner arm, poly-roll holder',
  },
  {
    id: 'TBL-MEC-501',
    name: 'Mechanic Heavy Tool Workbench (Buffer Workshop)',
    brand: 'WorkPro',
    model: 'MasterBench-Steel',
    category: 'TABLE',
    type: 'TABLE_PATTERN',
    typeName: 'Pattern Drafting & Master Table',
    purchaseDate: '2022-01-10',
    cost: 550,
    status: 'ACTIVE',
    currentLine: 'Buffer Workshop',
    stationNo: 'Bay B-01',
    operator: 'Ramesh Kumar',
    totalDowntimeMinutes: 0,
    ageYears: 4.7,
    specs: 'Solid 4mm steel plate top, integrated 6-inch swivel vice',
  },
  {
    id: 'TBL-SCRAP-01',
    name: 'Decommissioned Table Frame (Scrap Bay)',
    brand: 'Generic',
    model: 'Legacy-WoodTop',
    category: 'TABLE',
    type: 'TABLE_SEWING',
    typeName: 'Sewing Workstation Table',
    purchaseDate: '2017-06-15',
    cost: 150,
    status: 'SCRAP',
    currentLine: 'Scrap Bay',
    stationNo: 'Salvage Rack 02',
    operator: 'Decommissioned',
    totalDowntimeMinutes: 360,
    ageYears: 9.2,
    specs: 'Warped top, salvageable iron legs stored for frame spares',
  },

  // ==================== 3. ERGONOMIC CHAIRS & SEATING ====================
  {
    id: 'CHR-ERG-101',
    name: 'Ergonomic Operator Swivel Chair (Line 01 - St.04)',
    brand: 'Featherlite',
    model: 'Optima-Sew360',
    category: 'CHAIR',
    type: 'CHAIR_OPERATOR',
    typeName: 'Ergonomic Sewing Swivel Chair',
    purchaseDate: '2023-04-12',
    cost: 85,
    status: 'ACTIVE',
    currentLine: 'Line 01',
    stationNo: 'Station 04',
    operator: 'K. Kavitha',
    totalDowntimeMinutes: 0,
    ageYears: 3.4,
    specs: 'Pneumatic gas lift height adjust (42-56cm), lumbar support, PU foam',
  },
  {
    id: 'CHR-ERG-102',
    name: 'Ergonomic Operator Swivel Chair (Line 01 - St.07)',
    brand: 'Featherlite',
    model: 'Optima-Sew360',
    category: 'CHAIR',
    type: 'CHAIR_OPERATOR',
    typeName: 'Ergonomic Sewing Swivel Chair',
    purchaseDate: '2024-02-10',
    cost: 85,
    status: 'ACTIVE',
    currentLine: 'Line 01',
    stationNo: 'Station 07',
    operator: 'P. Rajeshwari',
    totalDowntimeMinutes: 0,
    ageYears: 2.6,
    specs: 'Armless for free upper body garment maneuvering, foot rest ring',
  },
  {
    id: 'CHR-ERG-201',
    name: 'Operator Ergonomic Chair (Line 02 - St.03)',
    brand: 'Featherlite',
    model: 'Optima-Sew360',
    category: 'CHAIR',
    type: 'CHAIR_OPERATOR',
    typeName: 'Ergonomic Sewing Swivel Chair',
    purchaseDate: '2022-09-18',
    cost: 85,
    status: 'BREAKDOWN',
    currentLine: 'Line 02',
    stationNo: 'Station 03',
    operator: 'S. Murugan',
    totalDowntimeMinutes: 60,
    ageYears: 4.0,
    specs: 'Hydraulic cylinder sinking under load - requires gas-lift replacement',
  },
  {
    id: 'CHR-ERG-202',
    name: 'Operator Ergonomic Chair (Line 02 - St.09)',
    brand: 'Featherlite',
    model: 'Optima-Sew360',
    category: 'CHAIR',
    type: 'CHAIR_OPERATOR',
    typeName: 'Ergonomic Sewing Swivel Chair',
    purchaseDate: '2021-11-05',
    cost: 85,
    status: 'ACTIVE',
    currentLine: 'Line 02',
    stationNo: 'Station 09',
    operator: 'D. Anitha',
    totalDowntimeMinutes: 0,
    ageYears: 4.9,
    specs: 'Breathable vinyl fabric resistant to machine lubricant mist',
  },
  {
    id: 'CHR-SUP-301',
    name: 'High-Back Supervisor Drafting Chair (Line 03)',
    brand: 'Godrej Interio',
    model: 'MotionDraft-High',
    category: 'CHAIR',
    type: 'CHAIR_SUPERVISOR',
    typeName: 'High-Back Supervisor Chair',
    purchaseDate: '2023-01-15',
    cost: 140,
    status: 'ACTIVE',
    currentLine: 'Line 03',
    stationNo: 'Station 01',
    operator: 'V. Selvam',
    totalDowntimeMinutes: 0,
    ageYears: 3.7,
    specs: 'Elevated height 68-82cm for line visibility, circular foot ring',
  },
  {
    id: 'CHR-ERG-401',
    name: 'Operator Heavy Swivel Chair (Line 04 - St.02)',
    brand: 'Featherlite',
    model: 'HeavyDuty-Task',
    category: 'CHAIR',
    type: 'CHAIR_OPERATOR',
    typeName: 'Ergonomic Sewing Swivel Chair',
    purchaseDate: '2023-05-15',
    cost: 95,
    status: 'ACTIVE',
    currentLine: 'Line 04',
    stationNo: 'Station 02',
    operator: 'R. Balamurugan',
    totalDowntimeMinutes: 0,
    ageYears: 3.3,
    specs: 'Dual-wheel nylon castors, heavy 150kg tested base',
  },
  {
    id: 'CHR-STL-501',
    name: 'Master Mechanic Swivel Stool (Buffer Workshop)',
    brand: 'Stanley',
    model: 'MechSeat-Pro',
    category: 'CHAIR',
    type: 'CHAIR_STOOL',
    typeName: 'Mechanic Workshop Stool',
    purchaseDate: '2022-01-10',
    cost: 70,
    status: 'ACTIVE',
    currentLine: 'Buffer Workshop',
    stationNo: 'Bay B-02',
    operator: 'Suresh Babu',
    totalDowntimeMinutes: 0,
    ageYears: 4.7,
    specs: 'Oil-resistant PU cushion with lower circular magnetic parts tray',
  },
  {
    id: 'CHR-SCRAP-01',
    name: 'Scrapped Damaged Stool (Scrap Bay)',
    brand: 'Generic',
    model: 'Legacy-Stool',
    category: 'CHAIR',
    type: 'CHAIR_STOOL',
    typeName: 'Mechanic Workshop Stool',
    purchaseDate: '2018-04-10',
    cost: 45,
    status: 'SCRAP',
    currentLine: 'Scrap Bay',
    stationNo: 'Salvage Rack 03',
    operator: 'Decommissioned',
    totalDowntimeMinutes: 240,
    ageYears: 8.4,
    specs: 'Cracked 5-star base, casters removed for spare parts',
  },

  // ==================== 4. INDUSTRIAL LIGHTING FIXTURES (UNDER UTILITIES) ====================
  {
    id: 'LGT-HBY-101',
    name: 'Overhead High-Bay Linear LED 150W (Line 01)',
    brand: 'Philips',
    model: 'CoreLine-HighBay-150',
    category: 'UTILITY',
    type: 'LIGHT_HIGHBAY',
    typeName: 'Overhead Linear High-Bay LED',
    purchaseDate: '2023-02-15',
    cost: 130,
    status: 'ACTIVE',
    currentLine: 'Line 01',
    stationNo: 'Overhead Bay 01',
    operator: 'Line 01 Shared',
    totalDowntimeMinutes: 0,
    ageYears: 3.6,
    specs: '150W, 18,000 Lumens, 6500K Cool Daylight, IP65 protection',
  },
  {
    id: 'LGT-TSK-101',
    name: 'Needle Point Task Gooseneck LED (Line 01 - St.04)',
    brand: 'Oshima',
    model: 'StitchBeam-30',
    category: 'UTILITY',
    type: 'LIGHT_TASK',
    typeName: 'Needle Station Gooseneck Lamp',
    purchaseDate: '2023-04-12',
    cost: 35,
    status: 'ACTIVE',
    currentLine: 'Line 01',
    stationNo: 'Station 04',
    operator: 'K. Kavitha',
    totalDowntimeMinutes: 0,
    ageYears: 3.4,
    specs: '30-LED magnetic clamp mount with flexible 360° goose arm, zero glare',
  },
  {
    id: 'LGT-HBY-201',
    name: 'Overhead High-Bay Linear LED 150W (Line 02)',
    brand: 'Philips',
    model: 'CoreLine-HighBay-150',
    category: 'UTILITY',
    type: 'LIGHT_HIGHBAY',
    typeName: 'Overhead Linear High-Bay LED',
    purchaseDate: '2022-08-10',
    cost: 130,
    status: 'ACTIVE',
    currentLine: 'Line 02',
    stationNo: 'Overhead Bay 02',
    operator: 'Line 02 Shared',
    totalDowntimeMinutes: 0,
    ageYears: 4.1,
    specs: 'Glare-reduction frosted polycarbonate diffuser, 50,000h lifespan',
  },
  {
    id: 'LGT-INSP-301',
    name: 'Color-Matching Inspection Light Strip (Line 03)',
    brand: 'VeriVide',
    model: 'ColorCheck-D65',
    category: 'UTILITY',
    type: 'LIGHT_INSPECTION',
    typeName: 'Color-Checking Inspection Tube',
    purchaseDate: '2023-01-15',
    cost: 240,
    status: 'ACTIVE',
    currentLine: 'Line 03',
    stationNo: 'Station 08',
    operator: 'A. Mary',
    totalDowntimeMinutes: 0,
    ageYears: 3.7,
    specs: 'CRI 98+ Ra rating, D65 artificial daylight for fabric shade matching',
  },
  {
    id: 'LGT-HBY-401',
    name: 'High-Bay Industrial Linear LED (Line 04)',
    brand: 'Wipro',
    model: 'OptiGlow-120',
    category: 'UTILITY',
    type: 'LIGHT_HIGHBAY',
    typeName: 'Overhead Linear High-Bay LED',
    purchaseDate: '2023-05-15',
    cost: 120,
    status: 'BREAKDOWN',
    currentLine: 'Line 04',
    stationNo: 'Overhead Bay 04',
    operator: 'Line 04 Shared',
    totalDowntimeMinutes: 120,
    ageYears: 3.3,
    specs: 'Driver ballast flickering on phase 2 circuit - capacitor swap required',
  },
  {
    id: 'LGT-INSP-501',
    name: 'Articulated Mechanic Bench Inspection Lamp (Buffer Bay)',
    brand: 'Osram',
    model: 'BenchBright-LED',
    category: 'UTILITY',
    type: 'LIGHT_TASK',
    typeName: 'Needle Station Gooseneck Lamp',
    purchaseDate: '2022-01-10',
    cost: 55,
    status: 'ACTIVE',
    currentLine: 'Buffer Workshop',
    stationNo: 'Bay B-01',
    operator: 'Ramesh Kumar',
    totalDowntimeMinutes: 0,
    ageYears: 4.7,
    specs: 'Heavy spring-loaded scissor arm with 3X magnifying lens ring',
  },

  // ==================== 5. FANS & VENTILATION / HVAC (UNDER UTILITIES) ====================
  {
    id: 'FAN-CEIL-101',
    name: 'Heavy Industrial Ceiling Fan 56" (Line 01)',
    brand: 'Havells',
    model: 'IndusAir-56',
    category: 'UTILITY',
    type: 'FAN_CEILING',
    typeName: 'Heavy Industrial Ceiling Fan',
    motorType: 'CLUTCH',
    purchaseDate: '2022-04-10',
    cost: 70,
    status: 'ACTIVE',
    currentLine: 'Line 01',
    stationNo: 'Zone A-01',
    operator: 'Line 01 Shared',
    totalDowntimeMinutes: 0,
    ageYears: 4.4,
    specs: '56-inch aluminum aero-blades, copper winding heavy motor, 320 RPM',
  },
  {
    id: 'FAN-PED-101',
    name: 'Floor Standing Pedestal Wind Blower (Line 01 - St.07)',
    brand: 'Almonard',
    model: 'AirMax-24P',
    category: 'UTILITY',
    type: 'FAN_PEDESTAL',
    typeName: 'High-Velocity Floor Pedestal Fan',
    motorType: 'CLUTCH',
    purchaseDate: '2023-06-15',
    cost: 95,
    status: 'ACTIVE',
    currentLine: 'Line 01',
    stationNo: 'Station 07',
    operator: 'P. Rajeshwari',
    totalDowntimeMinutes: 0,
    ageYears: 3.2,
    specs: '24-inch oscillation head, high air-delivery 14,000 m3/h',
  },
  {
    id: 'FAN-CEIL-201',
    name: 'Heavy Industrial Ceiling Fan 56" (Line 02)',
    brand: 'Crompton',
    model: 'FactoryAir-Heavy',
    category: 'UTILITY',
    type: 'FAN_CEILING',
    typeName: 'Heavy Industrial Ceiling Fan',
    motorType: 'CLUTCH',
    purchaseDate: '2022-08-10',
    cost: 70,
    status: 'ACTIVE',
    currentLine: 'Line 02',
    stationNo: 'Zone B-01',
    operator: 'Line 02 Shared',
    totalDowntimeMinutes: 0,
    ageYears: 4.1,
    specs: 'Double ball bearing, low vibration ceiling downrod',
  },
  {
    id: 'FAN-EXH-301',
    name: 'Wall-Mount Heavy Exhaust Blower (Line 03)',
    brand: 'Almonard',
    model: 'HeavyDuty-Exhaust-18',
    category: 'UTILITY',
    type: 'FAN_EXHAUST',
    typeName: 'Wall Exhaust Blower',
    motorType: 'CLUTCH',
    purchaseDate: '2023-01-15',
    cost: 155,
    status: 'ACTIVE',
    currentLine: 'Line 03',
    stationNo: 'Rear Vent 03',
    operator: 'Line 03 Shared',
    totalDowntimeMinutes: 0,
    ageYears: 3.7,
    specs: '18-inch 1400 RPM exhaust for fabric lint expulsion & air circulation',
  },
  {
    id: 'FAN-EXH-401',
    name: 'High-Capacity Denim Lint Exhaust Fan (Line 04)',
    brand: 'Almonard',
    model: 'DustStorm-24',
    category: 'UTILITY',
    type: 'FAN_EXHAUST',
    typeName: 'Wall Exhaust Blower',
    motorType: 'CLUTCH',
    purchaseDate: '2023-05-15',
    cost: 175,
    status: 'BREAKDOWN',
    currentLine: 'Line 04',
    stationNo: 'Duct Vent 04',
    operator: 'Line 04 Shared',
    totalDowntimeMinutes: 180,
    ageYears: 3.3,
    specs: 'V-belt slipping and bearing dry noise - requires lubrication & tensioning',
  },
  {
    id: 'FAN-EXH-501',
    name: 'Fume & Solvent Exhaust Hood Fan (Buffer Bay)',
    brand: 'Usha',
    model: 'TurboClean-12',
    category: 'UTILITY',
    type: 'FAN_EXHAUST',
    typeName: 'Wall Exhaust Blower',
    motorType: 'CLUTCH',
    purchaseDate: '2022-01-10',
    cost: 85,
    status: 'ACTIVE',
    currentLine: 'Buffer Workshop',
    stationNo: 'Vent Hood B-01',
    operator: 'Maintenance Shared',
    totalDowntimeMinutes: 0,
    ageYears: 4.7,
    specs: 'Spark-proof enclosure for safe solvent & degreaser cleaning',
  },

  // ==================== 6. CENTRAL UTILITIES & SAFETY ASSETS ====================
  {
    id: 'UTL-BLR-01',
    name: 'Central Industrial Steam Iron Generator Boiler',
    brand: 'Silver Star',
    model: 'SteamMaster-30KW',
    category: 'UTILITY',
    type: 'UTILITY_BOILER',
    typeName: 'Industrial Steam Generator',
    motorType: 'SERVO',
    purchaseDate: '2021-08-20',
    cost: 2800,
    status: 'ACTIVE',
    currentLine: 'Buffer Workshop',
    stationNo: 'Boiler Enclosure 01',
    operator: 'Plant Utility Staff',
    totalDowntimeMinutes: 30,
    ageYears: 5.1,
    specs: '30 kW electric steam boiler with 6 bar pressure output to all ironing lines',
  },
  {
    id: 'UTL-CMP-01',
    name: 'Rotary Screw Industrial Air Compressor',
    brand: 'Atlas Copco',
    model: 'G-11-FF',
    category: 'UTILITY',
    type: 'UTILITY_COMPRESSOR',
    typeName: 'Screw Air Compressor',
    motorType: 'SERVO',
    purchaseDate: '2022-03-05',
    cost: 3200,
    status: 'ACTIVE',
    currentLine: 'Buffer Workshop',
    stationNo: 'Compressor Bay 01',
    operator: 'Plant Utility Staff',
    totalDowntimeMinutes: 15,
    ageYears: 4.5,
    specs: '11 kW 10 bar continuous compressed air for pneumatic trimmers & lifters',
  },
  {
    id: 'UTL-SFT-101',
    name: 'Line 01 Emergency CO2 & ABC Fire Safety Station',
    brand: 'Ceasefire',
    model: 'QuickResponse-Twin',
    category: 'UTILITY',
    type: 'UTILITY_SAFETY',
    typeName: 'Line Fire Safety Station',
    purchaseDate: '2024-01-10',
    cost: 110,
    status: 'ACTIVE',
    currentLine: 'Line 01',
    stationNo: 'Column Head 01',
    operator: 'Safety Warden',
    totalDowntimeMinutes: 0,
    ageYears: 2.7,
    specs: 'Dual 4.5kg CO2 extinguisher (electrical) & ABC powder unit with pressure gauge',
  },

  // ==================== 7. CUTTING DEPARTMENT ASSETS ====================
  {
    id: 'MC-OVK-4TH-CUT01',
    name: 'Supreme 4-Thread Heavy Trimming Overlock (Cutting Dept)',
    brand: 'Supreme',
    model: 'SP-747D Heavy Cut',
    category: 'MACHINE',
    department: 'Cutting Department',
    machineClass: 'OVERLOCK',
    type: 'OVERLOCK_4_THREAD',
    typeName: '4 Thread Overlock',
    motorType: 'SERVO',
    purchaseDate: '2022-06-15',
    cost: 1250,
    status: 'ACTIVE',
    currentLine: 'Cutting Department',
    stationNo: 'Cutting Bay 01',
    operator: 'R. Periasamy',
    totalDowntimeMinutes: 15,
    ageYears: 4.2,
    specs: 'Heavy 4-thread overlock with integrated edge-trimming blade for pre-assembly edge cleaning',
  },
  {
    id: 'LGT-CUT-01',
    name: 'Cutting Hall High-CRI Linear Daylight Array',
    brand: 'Philips',
    model: 'MasterLED-Cut200',
    category: 'UTILITY',
    department: 'Cutting Department',
    type: 'LIGHT_HIGHBAY',
    typeName: 'Cutting Hall High-Bay LED',
    purchaseDate: '2023-03-10',
    cost: 160,
    status: 'ACTIVE',
    currentLine: 'Cutting Department',
    stationNo: 'Overhead Spreading Bay',
    operator: 'Cutting Crew',
    totalDowntimeMinutes: 0,
    ageYears: 3.5,
    specs: '200W, 24000 lumens, 6500K shadow-free illumination for fabric grain alignment',
  },

  // ==================== 8. FINISHING & PRESSING ASSETS ====================
  {
    id: 'TBL-PRS-01',
    name: 'Veit Industrial Vacuum & Blowing Ironing Table',
    brand: 'Veit',
    model: 'Vario-Set-4450',
    category: 'TABLE',
    department: 'Finishing & Pressing',
    type: 'TABLE_SEWING',
    typeName: 'Vacuum Pressing Table',
    purchaseDate: '2023-05-18',
    cost: 2100,
    status: 'ACTIVE',
    currentLine: 'Finishing & Pressing',
    stationNo: 'Ironing Deck 01',
    operator: 'K. Subramani',
    totalDowntimeMinutes: 20,
    ageYears: 3.3,
    specs: 'Foot-pedal controlled high-suction vacuum, heated buck surface, swivel sleeve arm',
  },
  {
    id: 'FAN-FIN-01',
    name: 'Finishing Section High-Volume Cooling Air Sweeper',
    brand: 'Almonard',
    model: 'HeavyBlower-30',
    category: 'UTILITY',
    department: 'Finishing & Pressing',
    type: 'FAN_PEDESTAL',
    typeName: 'Industrial Steam Dissipation Fan',
    purchaseDate: '2023-08-12',
    cost: 135,
    status: 'ACTIVE',
    currentLine: 'Finishing & Pressing',
    stationNo: 'Pressing Line A',
    operator: 'Finishing Team',
    totalDowntimeMinutes: 0,
    ageYears: 3.1,
    specs: '30-inch heavy duty blade, 18,000 CFM rapid steam and heat dispersion',
  },

  // ==================== 9. EMBROIDERY & PRINTING ASSETS ====================
  {
    id: 'MC-FLK-TOP-EMB01',
    name: 'Yamato Top Elastic Flatlock (Embroidery Unit)',
    brand: 'Yamato',
    model: 'VG-2790-ET Top Elastic Attacher',
    category: 'MACHINE',
    department: 'Embroidery & Printing',
    machineClass: 'FLATLOCK',
    type: 'FLATLOCK_TOP_ELASTIC',
    typeName: 'Top Elastic Flatlock',
    motorType: 'SERVO',
    purchaseDate: '2021-10-20',
    cost: 2350,
    status: 'ACTIVE',
    currentLine: 'Embroidery & Printing',
    stationNo: 'Embroidery Suite',
    operator: 'M. Senthil',
    totalDowntimeMinutes: 45,
    ageYears: 4.9,
    specs: 'Computerized stepping motor elastic tape meter & feed mechanism, right-edge fabric trimmer',
  },
  {
    id: 'TBL-PRT-01',
    name: 'M&R Manual Textile Screen Printing Carousel Table',
    brand: 'M&R',
    model: 'Kruzer-6C4S',
    category: 'TABLE',
    department: 'Embroidery & Printing',
    type: 'TABLE_PATTERN',
    typeName: 'Screen Printing Carousel Table',
    purchaseDate: '2022-11-14',
    cost: 3400,
    status: 'ACTIVE',
    currentLine: 'Embroidery & Printing',
    stationNo: 'Print Station 01',
    operator: 'N. Vignesh',
    totalDowntimeMinutes: 0,
    ageYears: 3.8,
    specs: '6-Color 4-Station rotary carousel, micro-registration system, solid cast aluminum platens',
  },

  // ==================== 10. QUALITY ASSURANCE & PACKING ====================
  {
    id: 'MC-SN-BTN-QC01',
    name: 'Brother Button Stitch QA Inspection & Rework Station',
    brand: 'Brother',
    model: 'BE-438F QA Station',
    category: 'MACHINE',
    department: 'Quality & Packing',
    machineClass: 'SINGLE_NEEDLE',
    type: 'SN_BROTHER_BUTTON_STITCH',
    typeName: 'Brother Button Stitch',
    motorType: 'SERVO',
    purchaseDate: '2023-07-22',
    cost: 1350,
    status: 'ACTIVE',
    currentLine: 'Quality & Packing',
    stationNo: 'Final QC Bay 01',
    operator: 'D. Kalpana',
    totalDowntimeMinutes: 0,
    ageYears: 3.1,
    specs: 'Lockstitch button attachment inspection, pull-force gauge check, and instant rework clamp',
  },

  // ==================== 11. WAREHOUSE & MATERIAL HANDLING ====================
  {
    id: 'LOG-FLK-01',
    name: 'Godrej 2.5 Ton Electric Hydraulic Pallet Truck',
    brand: 'Godrej',
    model: 'PT-25-Electric',
    category: 'UTILITY',
    department: 'Warehouse & Storage',
    type: 'UTILITY_SAFETY',
    typeName: 'Electric Hydraulic Pallet Truck',
    motorType: 'SERVO',
    purchaseDate: '2023-09-05',
    cost: 2900,
    status: 'ACTIVE',
    currentLine: 'Warehouse & Storage',
    stationNo: 'Loading Dock A',
    operator: 'Logistics Team',
    totalDowntimeMinutes: 10,
    ageYears: 3.0,
    specs: '2500 kg lift capacity, regenerative braking, 24V/210Ah traction battery pack',
  },
  {
    id: 'LOG-RCK-01',
    name: 'Heavy-Duty Fabric Roll Cantilever Racking System',
    brand: 'Godrej Storage',
    model: 'HeavyRoll-Rack-4T',
    category: 'TABLE',
    department: 'Warehouse & Storage',
    type: 'TABLE_PATTERN',
    typeName: 'Fabric Roll Storage Racking',
    purchaseDate: '2022-04-18',
    cost: 1800,
    status: 'ACTIVE',
    currentLine: 'Warehouse & Storage',
    stationNo: 'Aisle 03',
    operator: 'Warehouse Stores',
    totalDowntimeMinutes: 0,
    ageYears: 4.4,
    specs: '4-Tier structural steel cantilever arms, 6000 kg total rack capacity, anti-roll stoppers',
  },

  // ==================== 12. CENTRAL UTILITIES & PLANT ====================
  {
    id: 'UTL-GEN-01',
    name: 'Cummins 250 kVA Silent Diesel Generator Set (DG)',
    brand: 'Cummins',
    model: 'C250-D5',
    category: 'UTILITY',
    department: 'Central Utilities & Plant',
    type: 'UTILITY_BOILER',
    typeName: 'Emergency Backup Diesel Generator',
    motorType: 'CLUTCH',
    purchaseDate: '2021-04-10',
    cost: 14500,
    status: 'ACTIVE',
    currentLine: 'Central Utilities & Plant',
    stationNo: 'Powerhouse Bay 01',
    operator: 'Chief Electrical Officer',
    totalDowntimeMinutes: 0,
    ageYears: 5.4,
    specs: '250 kVA / 200 kW prime power, acoustic sound enclosure (75 dB at 1m), auto-mains failure panel',
  },
  {
    id: 'UTL-WTR-01',
    name: 'Industrial RO & Water Softening Plant for Steam Boilers',
    brand: 'Thermax',
    model: 'AquaSoft-2000',
    category: 'UTILITY',
    department: 'Central Utilities & Plant',
    type: 'UTILITY_SAFETY',
    typeName: 'Water Softening & Demineralizer',
    purchaseDate: '2022-02-15',
    cost: 3800,
    status: 'ACTIVE',
    currentLine: 'Central Utilities & Plant',
    stationNo: 'Water Treatment Plant',
    operator: 'Utility Operator',
    totalDowntimeMinutes: 0,
    ageYears: 4.6,
    specs: '2000 LPH flow rate, automatic brine regeneration, zero silica boiler feed guarantee',
  },

  // ==================== 13. MAINTENANCE WORKSHOP ASSETS ====================
  {
    id: 'MC-FLK-VT-MEC01',
    name: 'Yamato VT Flatlock (Master Mechanic Calibration Bed)',
    brand: 'Yamato',
    model: 'VT-1500-Pro High-Lift',
    category: 'MACHINE',
    department: 'Maintenance Workshop',
    machineClass: 'FLATLOCK',
    type: 'FLATLOCK_VT',
    typeName: 'VT Flatlock',
    motorType: 'SERVO',
    purchaseDate: '2020-05-12',
    cost: 2100,
    status: 'ACTIVE',
    currentLine: 'Maintenance Workshop',
    stationNo: 'Machining Bay 01',
    operator: 'Ramesh Kumar',
    totalDowntimeMinutes: 0,
    ageYears: 6.3,
    specs: 'Variable Top-feed coverstitch calibration testing stand for apprentice training and looper timing',
  },
];

export const SEED_PARTS: SparePart[] = [
  {
    partId: 'PRT-01',
    sku: 'NDL-DBX1-14',
    name: 'Organ Needles DBx1 (#14/90) for Single Needle',
    category: 'Needles',
    compat: 'Brother KAJA, Button Stitch, Bartack',
    stock: 380,
    minStock: 150,
    monthlyAllowance: 500,
    unitCost: 0.35,
    unit: 'pcs',
    compatibleTypes: ['SN_BROTHER_KAJA', 'SN_BROTHER_BUTTON_STITCH', 'SN_BROTHER_BARTACK', 'SNLS'],
  },
  {
    partId: 'PRT-02',
    sku: 'NDL-DCX27-11',
    name: 'Organ Needles DCx27 (#11/75) for Overlock',
    category: 'Needles',
    compat: 'Yamato & Supreme Overlock (4 Thread, Rib, LFC)',
    stock: 240,
    minStock: 100,
    monthlyAllowance: 300,
    unitCost: 0.4,
    unit: 'pcs',
    compatibleTypes: ['OVERLOCK_4_THREAD', 'OVERLOCK_RIB_THREAD', 'OVERLOCK_LFC', 'OVERLOCK'],
  },
  {
    partId: 'PRT-03',
    sku: 'LP-YAM-AZ',
    name: 'Yamato Overlock Upper & Lower Looper Set',
    category: 'Hooks & Loopers',
    compat: 'Yamato / Supreme 4-Thread & Rib Thread Overlock',
    stock: 4, // LOW STOCK
    minStock: 8,
    monthlyAllowance: 15,
    unitCost: 16.5,
    unit: 'units',
    compatibleTypes: ['OVERLOCK_4_THREAD', 'OVERLOCK_RIB_THREAD', 'OVERLOCK_LFC', 'OVERLOCK'],
  },
  {
    partId: 'PRT-04',
    sku: 'BC-BRO-KAJA',
    name: 'Brother Bobbin Case BC-DB1-NBL for KAJA & Bartack',
    category: 'Hooks & Loopers',
    compat: 'Brother KAJA, Button Stitch, Bartack',
    stock: 26,
    minStock: 15,
    monthlyAllowance: 40,
    unitCost: 8.5,
    unit: 'units',
    compatibleTypes: ['SN_BROTHER_KAJA', 'SN_BROTHER_BUTTON_STITCH', 'SN_BROTHER_BARTACK', 'BARTACK'],
  },
  {
    partId: 'PRT-05',
    sku: 'LP-FLK-VG',
    name: 'Yamato Flatlock Coverstitch Looper & Spreader',
    category: 'Hooks & Loopers',
    compat: 'Yamato Flatlock (Hemming, Cylinder Bed, Small Cylinder, Flat Bed, VT)',
    stock: 5,
    minStock: 6,
    monthlyAllowance: 12,
    unitCost: 18.0,
    unit: 'units',
    compatibleTypes: [
      'FLATLOCK_HEMMING',
      'FLATLOCK_SMALL_CYLINDER',
      'FLATLOCK_CYLINDER_BED',
      'FLATLOCK_FLAT_BED',
      'FLATLOCK_VT',
      'FLATLOCK_TOP_ELASTIC',
      'FLATLOCK',
    ],
  },
  {
    partId: 'PRT-06',
    sku: 'TP-OVK-E18',
    name: 'Overlock Throat / Needle Plate E18 Gauge',
    category: 'Feed & Plates',
    compat: 'Yamato / Supreme 4-Thread & LFC Overlock',
    stock: 12,
    minStock: 8,
    monthlyAllowance: 16,
    unitCost: 9.6,
    unit: 'units',
    compatibleTypes: ['OVERLOCK_4_THREAD', 'OVERLOCK_RIB_THREAD', 'OVERLOCK_LFC', 'OVERLOCK'],
  },
  {
    partId: 'PRT-07',
    sku: 'MOT-DD-PCB',
    name: 'Direct-Drive Servo Main Driver Board PCB',
    category: 'Motors & Electrical',
    compat: 'Yamato, Brother & Supreme Direct-Drive Units',
    stock: 2,
    minStock: 2,
    monthlyAllowance: 4,
    unitCost: 110.0,
    unit: 'units',
    compatibleTypes: [
      'OVERLOCK_4_THREAD',
      'OVERLOCK_RIB_THREAD',
      'OVERLOCK_LFC',
      'FLATLOCK_HEMMING',
      'FLATLOCK_SMALL_CYLINDER',
      'FLATLOCK_CYLINDER_BED',
      'FLATLOCK_FLAT_BED',
      'FLATLOCK_VT',
      'FLATLOCK_TOP_ELASTIC',
      'SN_BROTHER_KAJA',
      'SN_BROTHER_BUTTON_STITCH',
      'SN_BROTHER_BARTACK',
    ],
  },
  {
    partId: 'PRT-08',
    sku: 'OIL-VG10-5L',
    name: 'High Purity White Sewing Mineral Oil (ISO VG 10, 5L)',
    category: 'Fluids & Consumables',
    compat: 'Universal Lubrication for Overlock, Flatlock, and Single Needle',
    stock: 16,
    minStock: 8,
    monthlyAllowance: 24,
    unitCost: 22.5,
    unit: 'jugs',
    compatibleTypes: [
      'OVERLOCK_4_THREAD',
      'OVERLOCK_RIB_THREAD',
      'OVERLOCK_LFC',
      'FLATLOCK_HEMMING',
      'FLATLOCK_SMALL_CYLINDER',
      'FLATLOCK_CYLINDER_BED',
      'FLATLOCK_FLAT_BED',
      'FLATLOCK_VT',
      'FLATLOCK_TOP_ELASTIC',
      'SN_BROTHER_KAJA',
      'SN_BROTHER_BUTTON_STITCH',
      'SN_BROTHER_BARTACK',
    ],
  },
  {
    partId: 'PRT-09',
    sku: 'NDL-UY128-11',
    name: 'Organ Needles UY128GAS (#11/75) for Flatlock',
    category: 'Needles',
    compat: 'Yamato Flatlock Coverstitch Series',
    stock: 280,
    minStock: 100,
    monthlyAllowance: 400,
    unitCost: 0.45,
    unit: 'pcs',
    compatibleTypes: [
      'FLATLOCK_HEMMING',
      'FLATLOCK_SMALL_CYLINDER',
      'FLATLOCK_CYLINDER_BED',
      'FLATLOCK_FLAT_BED',
      'FLATLOCK_VT',
      'FLATLOCK_TOP_ELASTIC',
      'FLATLOCK',
    ],
  },
  {
    partId: 'PRT-10',
    sku: 'KNF-OVK-LWR',
    name: 'Carbide Lower Stationary Trimming Knife',
    category: 'Feed & Plates',
    compat: 'Yamato & Supreme Overlock Trimmer Unit',
    stock: 7,
    minStock: 8, // LOW STOCK
    monthlyAllowance: 14,
    unitCost: 8.75,
    unit: 'pcs',
    compatibleTypes: ['OVERLOCK_4_THREAD', 'OVERLOCK_RIB_THREAD', 'OVERLOCK_LFC', 'OVERLOCK'],
  },
];

export const SEED_REPAIRS: RepairTicket[] = [
  {
    id: 'WO-1091',
    machineId: 'MC-OVK-4TH-204',
    machineType: '4 Thread Overlock',
    line: 'Line 02',
    reportedAt: '2026-09-21T08:30:00Z',
    reportedBy: 'S. Murugan (Supervisor)',
    faultCategory: 'Looper / Timing Misalignment',
    faultDetails: 'Skipping stitches on 4-thread knit poly t-shirt seam. Upper looper clashing with needle tip on high speed.',
    urgency: 'CRITICAL',
    status: 'IN_PROGRESS',
    attendedBy: 'Ramesh Kumar',
    resolvedAt: null,
    downtimeMinutes: 45,
    actionTaken: '',
    partsUsed: [],
  },
  {
    id: 'WO-1085',
    machineId: 'MC-SN-BTK-102',
    machineType: 'Brother Bartack',
    line: 'Line 01',
    reportedAt: '2026-09-20T16:15:00Z',
    reportedBy: 'P. Rajeshwari (Operator)',
    faultCategory: 'Thread Tension / Skipping',
    faultDetails: 'Birdnesting and uneven tension on under-thread seam. Tension release disc sluggish.',
    urgency: 'WARNING',
    status: 'PENDING',
    attendedBy: null,
    resolvedAt: null,
    downtimeMinutes: 0,
    actionTaken: '',
    partsUsed: [],
  },
  {
    id: 'HIST-902',
    machineId: 'MC-SN-KAJA-101',
    machineType: 'Brother KAJA',
    line: 'Line 01',
    reportedAt: '2026-09-12T10:00:00Z',
    reportedBy: 'K. Kavitha (Operator)',
    faultCategory: 'Needle Breakage',
    faultDetails: 'Needle bar height slippage causing frequent needle strikes against buttonhole cutter plate.',
    urgency: 'CRITICAL',
    status: 'COMPLETED',
    attendedBy: 'Ramesh Kumar',
    resolvedAt: '2026-09-12T10:25:00Z',
    downtimeMinutes: 25,
    actionTaken: 'Calibrated needle bar timing mark to 1.8mm above hook point. Re-torqued buttonhole indexer clamp.',
    partsUsed: [
      {
        partId: 'PRT-01',
        sku: 'NDL-DBX1-14',
        name: 'Organ Needles DBx1 (#14/90) for Single Needle',
        quantity: 1,
      },
    ],
  },
  {
    id: 'HIST-879',
    machineId: 'MC-SN-KAJA-101',
    machineType: 'Brother KAJA',
    line: 'Line 01',
    reportedAt: '2026-08-20T14:00:00Z',
    reportedBy: 'System Routine',
    faultCategory: 'Oil Leakage',
    faultDetails: 'Oil reservoir filter clogged with fabric lint and wick dried.',
    urgency: 'WARNING',
    status: 'COMPLETED',
    attendedBy: 'Ramesh Kumar',
    resolvedAt: '2026-08-20T14:15:00Z',
    downtimeMinutes: 15,
    actionTaken: 'Purged lint beneath indexer plate. Refilled reservoir with 0.5L ISO VG 10 sewing oil.',
    partsUsed: [
      {
        partId: 'PRT-08',
        sku: 'OIL-VG10-5L',
        name: 'High Purity White Sewing Mineral Oil (ISO VG 10, 5L)',
        quantity: 1,
      },
    ],
  },
  {
    id: 'HIST-840',
    machineId: 'MC-SN-KAJA-101',
    machineType: 'Brother KAJA',
    line: 'Line 01',
    reportedAt: '2026-07-04T09:30:00Z',
    reportedBy: 'K. Kavitha (Operator)',
    faultCategory: 'Motor / Drive Error',
    faultDetails: 'Under-bed Thread Trimmer (UTT) jam and solenoid stroke error.',
    urgency: 'CRITICAL',
    status: 'COMPLETED',
    attendedBy: 'Ramesh Kumar',
    resolvedAt: '2026-07-04T10:15:00Z',
    downtimeMinutes: 45,
    actionTaken: 'Replaced movable thread cutter blade and reset solenoid stroke and safety interlock.',
    partsUsed: [
      {
        partId: 'PRT-04',
        sku: 'BC-BRO-KAJA',
        name: 'Brother Bobbin Case BC-DB1-NBL for KAJA & Bartack',
        quantity: 1,
      },
    ],
  },
  {
    id: 'HIST-790',
    machineId: 'MC-OVK-4TH-204',
    machineType: '4 Thread Overlock',
    line: 'Line 02',
    reportedAt: '2026-08-29T11:20:00Z',
    reportedBy: 'S. Murugan (Supervisor)',
    faultCategory: 'Needle Breakage',
    faultDetails: 'Differential feed dog slipping and needle plate burr cutting thread.',
    urgency: 'WARNING',
    status: 'COMPLETED',
    attendedBy: 'Ramesh Kumar',
    resolvedAt: '2026-08-29T11:55:00Z',
    downtimeMinutes: 35,
    actionTaken: 'Re-torqued eccentric feed cam screw, deburred plate throat, and honed upper knife edge.',
    partsUsed: [
      {
        partId: 'PRT-06',
        sku: 'TP-OVK-E18',
        name: 'Overlock Throat / Needle Plate E18 Gauge',
        quantity: 1,
      },
    ],
  },
];

export const SEED_PPM_SCHEDULES: PPMSchedule[] = [
  {
    id: 'SCH-01',
    machineId: 'MC-SN-KAJA-101',
    task: 'Weekly Blower Lint Purge & Tension Washer Check',
    intervalDays: 7,
    frequency: 'Weekly',
    lastServiced: '2026-09-17',
    nextDue: '2026-09-24',
    status: 'PENDING',
  },
  {
    id: 'SCH-02',
    machineId: 'MC-SN-KAJA-101',
    task: 'Monthly Oil Filter Screen Cleaning & Wick Flush',
    intervalDays: 30,
    frequency: 'Monthly',
    lastServiced: '2026-08-23',
    nextDue: '2026-09-22',
    status: 'DUE_SOON',
  },
  {
    id: 'SCH-03',
    machineId: 'MC-SN-KAJA-101',
    task: 'Semi-Annual Hook Timing & Needle Bar Clearance Audit',
    intervalDays: 180,
    frequency: '6-Month',
    lastServiced: '2026-04-15',
    nextDue: '2026-10-15',
    status: 'PENDING',
  },
  {
    id: 'SCH-04',
    machineId: 'MC-OVK-4TH-204',
    task: 'Bi-Weekly Looper Clearance & Differential Feed Calibration',
    intervalDays: 14,
    frequency: 'Weekly',
    lastServiced: '2026-09-10',
    nextDue: '2026-09-24',
    status: 'PENDING',
  },
  {
    id: 'SCH-05',
    machineId: 'MC-SN-BTN-501',
    task: 'Monthly Button Clamp Alignment & Oil Reservoir Check',
    intervalDays: 30,
    frequency: 'Monthly',
    lastServiced: '2026-08-21',
    nextDue: '2026-09-21',
    status: 'DUE_SOON',
  },
];

export const SEED_REQUISITIONS: PartRequisition[] = [
  {
    id: 'REQ-2026-091',
    type: 'CRITICAL_CEO',
    partId: 'PRT-07',
    partName: 'Direct-Drive Servo Main Driver Board PCB',
    sku: 'MOT-DD-PCB',
    quantity: 2,
    unit: 'units',
    itemCount: 1,
    estimatedCost: 220.0,
    urgency: 'CRITICAL_CEO_APPROVAL',
    requiresCeoApproval: true,
    requestedBy: 'Ramesh Kumar',
    requestedByRole: 'Lead Sewing Mechanic',
    monthYear: 'September 2026',
    targetLine: 'Line 02',
    targetMachineId: 'MC-OVK-204',
    justification: 'CRITICAL LINE STOPPAGE: High-voltage surge blew controller circuit on Line 02 Pegasus overlock. Zero backup boards in tool crib. Entire polo tee batch halted. Requires immediate CEO budget sign-off.',
    status: 'PENDING_CEO_APPROVAL',
    createdAt: '2026-09-21T09:15:00Z',
  },
  {
    id: 'REQ-2026-095',
    type: 'URGENT_NEED',
    partId: 'PRT-03',
    partName: 'Upper Looper (Pegasus M900 Series)',
    sku: 'LP-PEG-M900',
    quantity: 6,
    unit: 'units',
    itemCount: 1,
    estimatedCost: 85.2,
    urgency: 'URGENT_MANAGER',
    requiresCeoApproval: false,
    requestedBy: 'Ramesh Kumar',
    requestedByRole: 'Lead Sewing Mechanic',
    monthYear: 'September 2026',
    targetLine: 'Line 02',
    targetMachineId: 'MC-OVK-204',
    justification: 'URGENT SHIFT DEFECT: Frequent needle-looper clash causing burrs. Stock down to 4 loopers across entire plant. Requires fast-track maintenance manager authorization.',
    status: 'PENDING_MANAGER_APPROVAL',
    createdAt: '2026-09-21T10:30:00Z',
  },
  {
    id: 'REQ-2026-088',
    type: 'MONTHLY_INDENT',
    items: [
      {
        partId: 'PRT-01',
        partName: 'Organ Needles DBx1 (#14/90) Knit & Woven',
        sku: 'NDL-DBX1-14',
        quantity: 500,
        unit: 'pcs',
        unitCost: 0.35,
        totalCost: 175.0,
      },
      {
        partId: 'PRT-08',
        partName: 'High Purity White Sewing Mineral Oil (ISO VG 10, 5L)',
        sku: 'OIL-VG10-5L',
        quantity: 10,
        unit: 'jugs',
        unitCost: 22.5,
        totalCost: 225.0,
      },
      {
        partId: 'PRT-04',
        partName: 'Bobbin Case Towa BC-DB1-NBL6',
        sku: 'BC-TOWA-BC1',
        quantity: 15,
        unit: 'units',
        unitCost: 7.8,
        totalCost: 117.0,
      },
      {
        partId: 'PRT-05',
        partName: 'Differential Feed Dog (4-Row Fine Pitch)',
        sku: 'FD-4ROW-JUK',
        quantity: 8,
        unit: 'units',
        unitCost: 6.4,
        totalCost: 51.2,
      },
    ],
    itemCount: 4,
    estimatedCost: 568.2,
    urgency: 'ROUTINE',
    requiresCeoApproval: false,
    requestedBy: 'Ramesh Kumar',
    requestedByRole: 'Lead Sewing Mechanic',
    monthYear: 'October 2026',
    targetLine: 'Line 01 & Line 03',
    justification: 'Planned monthly spare parts requirement for upcoming 50,000 unit export order on Line 01 and Line 03.',
    status: 'APPROVED_BY_MANAGER',
    createdAt: '2026-09-18T11:30:00Z',
    reviewedBy: 'V. Sundaram (Asset Manager)',
    reviewedAt: '2026-09-19T08:45:00Z',
    reviewNotes: 'Standard quota approved within monthly maintenance OPEX allocation.',
    assignedStorePerson: 'M. Arumugam (Stores In-Charge)',
  },
  {
    id: 'REQ-2026-089',
    type: 'MONTHLY_INDENT',
    items: [
      {
        partId: 'PRT-06',
        partName: 'Overlock Throat Plate E18 Gauge',
        sku: 'TP-OVK-E18',
        quantity: 10,
        unit: 'units',
        unitCost: 9.6,
        totalCost: 96.0,
      },
      {
        partId: 'PRT-10',
        partName: 'Carbide Lower Stationary Trimming Knife',
        sku: 'KNF-OVK-LWR',
        quantity: 12,
        unit: 'pcs',
        unitCost: 8.75,
        totalCost: 105.0,
      },
      {
        partId: 'PRT-09',
        partName: 'Non-Stick Teflon Hinged Presser Foot T350',
        sku: 'FT-TEFLON-T35',
        quantity: 15,
        unit: 'pcs',
        unitCost: 4.2,
        totalCost: 63.0,
      },
    ],
    itemCount: 3,
    estimatedCost: 264.0,
    urgency: 'ROUTINE',
    requiresCeoApproval: false,
    requestedBy: 'Ramesh Kumar',
    requestedByRole: 'Lead Sewing Mechanic',
    monthYear: 'October 2026',
    targetLine: 'Universal Plant',
    justification: 'Monthly overhaul batch: Trimming knives, needle plates and teflon feet for sheer fabric run.',
    status: 'PENDING_REVIEW',
    createdAt: '2026-09-20T14:20:00Z',
    assignedStorePerson: 'M. Arumugam (Stores In-Charge)',
  },
  {
    id: 'REQ-2026-092',
    type: 'CRITICAL_CEO',
    partId: 'PRT-02',
    partName: 'Rotary Hook Hirose Koban HSH-7.94BTR',
    sku: 'HK-KOB-794',
    quantity: 4,
    unit: 'units',
    itemCount: 1,
    estimatedCost: 114.0,
    urgency: 'CRITICAL_CEO_APPROVAL',
    requiresCeoApproval: true,
    requestedBy: 'Suresh Babu',
    requestedByRole: 'Line Sewing Mechanic',
    monthYear: 'September 2026',
    targetLine: 'Line 01',
    targetMachineId: 'MC-SN-KAJA-101',
    justification: 'LINE 01 SHIFT STOPPAGE: Indexer drive fractured during high-speed run on woven export batch. Emergency purchase authorization required by CEO to restore main garment line.',
    status: 'PENDING_CEO_APPROVAL',
    createdAt: '2026-09-21T11:45:00Z',
  },
];

